#!/usr/bin/env bash
# Regenerate web/appcast.xml for a notarized release DMG, EdDSA-signed with the Sparkle key.
# Run this AFTER the DMG is built + notarized and attached to its GitHub release, then commit
# web/appcast.xml (it auto-deploys to https://lineup.caiano.com/appcast.xml).
#
# Usage: ./Scripts/sparkle-appcast.sh <path-to-dmg> [version] [build]
#   version/build default to Resources/Info.plist (the just-released values).
#
# Requires: the EdDSA PRIVATE key in your login Keychain (run Scripts/sparkle-keygen.sh once).
# The enclosure points at the GitHub release asset, so upload the DMG there first.
set -euo pipefail
cd "$(dirname "$0")/.."

DMG="${1:?usage: sparkle-appcast.sh <dmg> [version] [build]}"
[ -f "${DMG}" ] || { echo "no such DMG: ${DMG}" >&2; exit 1; }

# Sparkle's CLI ships inside the SwiftPM artifact; build once so it's present.
swift build >/dev/null 2>&1 || true
SIGN_UPDATE="$(find .build/artifacts -type f -name sign_update -not -path '*old_dsa*' 2>/dev/null | head -1)"
[ -x "${SIGN_UPDATE}" ] || { echo "error: sign_update not found; run 'swift build' first." >&2; exit 1; }

VERSION="${2:-$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' Resources/Info.plist)}"
BUILD="${3:-$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' Resources/Info.plist)}"

# FAIL CLOSED: only ever EdDSA-sign a real, notarized, stapled Developer ID DMG. Once an
# enclosure lands in web/appcast.xml, Sparkle clients trust its archive signature and install it
# without a Gatekeeper prompt — so appcasting an unsigned / pre-notarization / ad-hoc / stale DMG
# by accident would hand auto-update users a binary that bypassed the guarantees a normal
# download enforces. Require the same acceptance as a release before signing.
# (Capture codesign output first: piping it into `grep -q` makes codesign die with SIGPIPE under
# `set -o pipefail`, a false negative.)
sig_info="$(codesign -dvvv "${DMG}" 2>&1 || true)"
if ! grep -q 'Authority=Developer ID Application' <<<"${sig_info}"; then
  echo "error: ${DMG} is not Developer ID-signed; refusing to appcast it." >&2; exit 1
fi
if ! spctl -a -vvv -t open --context context:primary-signature "${DMG}" 2>/dev/null; then
  echo "error: ${DMG} is not notarized / not accepted by Gatekeeper; refusing to appcast it." >&2; exit 1
fi
if ! xcrun stapler validate "${DMG}" >/dev/null 2>&1; then
  echo "error: ${DMG} is not stapled; run ./Scripts/notarize.sh \"${DMG}\" first." >&2; exit 1
fi

# sign_update prints e.g.  sparkle:edSignature="…" length="12345"
# (it reads the private key from the Keychain; fails loudly if the key is missing).
SIG_LINE="$("${SIGN_UPDATE}" "${DMG}")"

URL="https://github.com/hcaiano/lineup/releases/download/v${VERSION}/$(basename "${DMG}")"
NOTES="https://github.com/hcaiano/lineup/releases/tag/v${VERSION}"
DATE="$(date -u +'%a, %d %b %Y %H:%M:%S +0000')"

cat > web/appcast.xml <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Sparkle update feed for Lineup. Regenerated by Scripts/sparkle-appcast.sh per release. -->
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Lineup</title>
    <link>https://lineup.caiano.com/appcast.xml</link>
    <description>Updates for Lineup, a macOS window manager.</description>
    <language>en</language>
    <item>
      <title>Lineup ${VERSION}</title>
      <link>${NOTES}</link>
      <sparkle:version>${BUILD}</sparkle:version>
      <sparkle:shortVersionString>${VERSION}</sparkle:shortVersionString>
      <sparkle:releaseNotesLink>${NOTES}</sparkle:releaseNotesLink>
      <sparkle:minimumSystemVersion>13.0</sparkle:minimumSystemVersion>
      <pubDate>${DATE}</pubDate>
      <enclosure url="${URL}" type="application/octet-stream" ${SIG_LINE} />
    </item>
  </channel>
</rss>
XML

echo "==> wrote web/appcast.xml for Lineup ${VERSION} (build ${BUILD})"
echo "    enclosure: ${URL}"
echo "    Next: confirm the DMG is uploaded to that GitHub release, then commit web/appcast.xml"
echo "    (it auto-deploys to https://lineup.caiano.com/appcast.xml)."
